# Generated by Django 2.2.4 on 2020-12-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_age',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
