# Generated by Django 2.2.4 on 2020-12-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dog_dog_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='img',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
