# Generated by Django 2.2.4 on 2020-12-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201214_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('dogs_owned', models.IntegerField()),
                ('description', models.TextField()),
                ('reason_why', models.TextField()),
                ('occupataion', models.CharField(max_length=60)),
            ],
        ),
    ]
