# Generated by Django 2.2.4 on 2020-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_price',
            field=models.IntegerField(default=3000),
        ),
    ]
