# Generated by Django 2.2.4 on 2020-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dog_dog_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dog',
            field=models.CharField(default='none selected', max_length=50),
        ),
    ]
